spring:
  output:
    ansi:
      enabled: ALWAYS #控制台彩色输出
  # 加上此配置可自动配置安全验证及JWT验证
  autoconfigure:
    #    # TODO: remove when fixed https://github.com/spring-projects/spring-security/issues/6314
    exclude: org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*" # 允许访问的头信息,*表示全部
            maxAge: 1800  # 预检请求的缓存时间（秒），即在这个时间段里，对于相同的跨域请求不会再预检了
            allowedOrigins: "*" # 允许向该服务器提交请求的URI，*表示全部允许。。这里尽量限制来源域，比如http://xxxx:8080 ,以降低安全风险
            allowCredentials: true  # 允许cookies跨域
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      #        defaultFilters:
      #          - PreserveHostHeader # 将原始的http头部带上
      routes:
        - id: product
          uri: lb://product
          predicates:
            #            - Method=POST, PUT, PATCH, DELETE,GET
            - Path=/product/**
          filters:
            - StripPrefix=1
        - id: goods
          uri: lb://goods
          predicates:
            - Path=/goods/**
          filters:
            - StripPrefix=1
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
logging:
  level:
    org:
      springframework: INFO
    com:
      alibaba:
        nacos: ERROR


