spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:pubkey.pub
      client:
        registration:
          user-server:
            provider: user-server
            client-id: user
            client-secret: user
            authorization-grant-type: client_credentials
            scope: read,write,user:write
        provider:
          user-server:
            authorization-uri: http://localhost:8090/oauth/authorize
            token-uri: http://localhost:8090/oauth/token

logging:
  level:
    org:
      springframework: INFO
    com:
      alibaba:
        nacos: ERROR