server:
  port: 8082
  # 授权服务和客户端在同一个域名下会出现authorization_request_not_found错误 session=null 方案1 使用不同地址 2 修改session名称
  servlet:
    session:
      cookie:
        name: c2

logging:
  level:
    org:
      springframework: INFO
    com:
      alibaba:
        nacos: ERROR

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          c2:
            provider: uaa
            client-id: client2
            client-secret: client2
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: all
        provider:
          uaa:
            authorization-uri: http://localhost:8090/oauth/authorize
            token-uri: http://localhost:8090/oauth/token
            user-info-uri: http://localhost:8071/userinfo
            user-name-attribute: name
            jwk-set-uri: http://localhost:8090/token_keys

