spring:
  output:
    ansi:
      enabled: ALWAYS #控制台彩色输出

  # 加上此配置可自动配置安全验证及JWT验证
  #  redis:
  #    port: 6379
  #    host: 127.0.0.1
  #    # Redis服务器连接密码（默认为空）
  #    #    database:
  #    password: root

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*" # 允许访问的头信息,*表示全部
            maxAge: 1800  # 预检请求的缓存时间（秒），即在这个时间段里，对于相同的跨域请求不会再预检了
            allowedOrigins: "*" # 允许向该服务器提交请求的URI，*表示全部允许。。这里尽量限制来源域，比如http://xxxx:8080 ,以降低安全风险
            allowCredentials: true  # 允许cookies跨域
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      defaultFilters:
        #        - PreserveHostHeader # 将原始的http头部带上
        - RemoveRequestHeader=Cookie  # 清除Cookie 资源服务器不需要cookie 只需要token
      routes:
        - id: product
          uri: lb://product
          predicates:
            #            - Method=POST, PUT, PATCH, DELETE,GET
            - Path=/product/**
          filters:
            - StripPrefix=1
        - id: goods
          uri: lb://goods
          predicates:
            - Path=/goods/**
          filters:
            - StripPrefix=1
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
  #        - id: uaa
  #          uri: lb://uaa
  #          predicates:
  #            - Path=/login/**
  #          filters:
  #            - RemoveRequestHeader=device_type
  #           - RemoveRequestParameter=red
  security:
    oauth2:
      client:
        registration:
          mobile:
            provider: uaa
            client-id: mobile
            client-secret: mobile
            client-name: "mobile"
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/callback"
            scope: all
          client1:
            provider: uaa
            client-id: client1
            client-secret: client1
            client-name: "client1"
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: all
        provider:
          uaa:
            authorization-uri: http://localhost:8090/oauth/authorize
            token-uri: http://localhost:8090/oauth/token
            user-info-uri: http://localhost:8090/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://localhost:8090/oauth/token_key

logging:
  level:
    org:
      springframework: INFO  # INFO TRACE
    com:
      alibaba:
        nacos: ERROR


