server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8


spring:
  application:
    name: test
  main:
    allow-bean-definition-overriding: true

    # 热部署开关，false即不启用热部署
  devtools:
    restart:
      enabled: true
      # 指定热部署的目录
      additional-paths: src/main/java
      # 指定目录不更新
      exclude: test/**

  messages:
    encoding: UTF-8
  output:
    ansi:
      enabled: ALWAYS #控制台彩色输出
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true&nullNamePatternMatchesAll=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: test
    password: test
    #    type: com.zaxxer.hikari.HikariDataSource
    sql-script-encoding: UTF-8
    hikari:
      ##  Hikari 连接池配置 ------ 详细配置请访问：https://github.com/brettwooldridge/HikariCP
      ## 最小空闲连接数量
      minimum-idle: 5
      #      data-source-properties:
      #        stringtype: unspecified
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 10
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 连接池名称
      pool-name: hikariDshuiDbPool
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
#    schema: classpath:schema.sql # 表初始化
#    #    data: classpath:data.sql # 数据初始化
#    initialization-mode: always # 初始化模式  always为始终执行初始化，embedded只初始化内存数据库（默认值）,如h2等，never为不执行初始化


logging:
  level:
    #    org.springframework.cloud.gateway: TRACE
    org.springframework.http: DEBUG
    org.springframework.web: DEBUG
    com.alibaba.nacos: ERROR
    com.zaxxer.hikari: ERROR
    #    org.springframework.http.server.reactive: DEBUG
    #    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    com.dshui: INFO
    cc.dshui: INFO
    com.iit: INFO

#mybatis:
#  #  mapper-locations: classpath:com/iit/**/mapper/**.xml,classpath:com/dshui/**/**.xml
#  type-handlers-package:
##  config-location: classpath:mybatis.xml