server:
  #  address: 127.0.0.1
  port: 8090
  #  servlet:
  #    context-path: /uaa
  servlet:
    session:
      cookie:
        name: s0
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: uaa
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: ALWAYS #控制台彩色输出
  #  session:
  #    store-type: redis
  #  redis:
  #    port: 6379
  #    host: 127.0.0.1
  #    password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:pubkey.pub
      client:
        registration:
          uaa-client:
            provider: spring
            client-id: uaa-client
            client-secret: uaa-client
            authorization-grant-type: client_credentials
            scope: all
            client-name: uaa-client
        provider:
          spring:
            authorization-uri: http://localhost:8090/oauth/authorize
            token-uri: http://localhost:8090/oauth/token
#            issuer-uri:  http://localhost:8090
#  config:
#    activate:
#      on-profile: local
resource-uri: http://127.0.0.1:8071/user/auth

logging:
  level:
    web: INFO
    org:
      springframework: INFO # INFO TRACE
    io.lettuce.core: ERROR
    #      springframework: DEBUG
    com:
      alibaba:
        nacos: ERROR
