server:
  #  address: 127.0.0.1
  port: 8090
  #  servlet:
  #    context-path: /uaa
  servlet:
    session:
      cookie:
        name: auth
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: mall-auth-service
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: ALWAYS #控制台彩色输出
  session:
    store-type: redis
    redis:
      namespace: spring:auth:session
  redis:
    port: 6379
    host: 127.0.0.1
    password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:pubkey.pub
      client:
        registration:
          cms:
            provider: uaa
            client-id: auth
            client-secret: auth
            client-name: "授权"
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: all
#            scope: openId
        provider:
          uaa:
            authorization-uri: http://localhost:8091/oauth/authorize
            token-uri: http://localhost:8091/oauth/token
            user-info-uri: http://localhost:8091/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://localhost:8091/oauth/token_key

logging:
  level:
    org:
      springframework: INFO # INFO TRACE
    io.lettuce.core: ERROR
    #      springframework: DEBUG
    com:
      alibaba:
        nacos: ERROR
