server:
  port: 9091
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: erp
  main:
    allow-bean-definition-overriding: true

    # 热部署开关，false即不启用热部署
  devtools:
    restart:
      enabled: true
      # 指定热部署的目录
      additional-paths: src/main/java
      # 指定目录不更新
      exclude: test/**

  messages:
    encoding: UTF-8
  output:
    ansi:
      enabled: ALWAYS #控制台彩色输出
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/test
    username: root
    password: root

logging:
  level:
    #    org.springframework.cloud.gateway: TRACE
    org.springframework.http: DEBUG
    org.springframework.web: DEBUG
    com.alibaba.nacos: ERROR
    com.zaxxer.hikari: ERROR
    #    org.springframework.http.server.reactive: DEBUG
    #    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    com.dshui: INFO
    cc.dshui: INFO
    com.iit: INFO


#mybatis:
#  #  mapper-locations: classpath:com/iit/**/mapper/**.xml,classpath:com/dshui/**/**.xml
#  type-handlers-package:
##  config-location: classpath:mybatis.xml