server:
  port: 8081
  # 授权服务和客户端在同一个域名下会出现authorization_request_not_found错误 session=null 方案1 使用不同地址 2 修改session名称
  servlet:
    session:
      cookie:
        name: c1
#  forward-headers-strategy: framework
#  servlet:
#    session:
#      persistent: true

logging:
  level:
    org:
      springframework: INFO #TRACE # INFO
    com:
      alibaba:
        nacos: ERROR

spring:
  session:
    store-type: redis
#    redis:
#      flush-mode: on_save
#      namespace: client:session
  redis:
    port: 6379
    host: 127.0.0.1
    password: root

  security:
    oauth2:
      client:
        registration:
          c1:
            provider: uaa
            client-id: client1
            client-secret: client1
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: all
        provider:
          uaa:
            authorization-uri: http://localhost:8090/oauth/authorize
            token-uri: http://localhost:8090/oauth/token
            user-info-uri: http://localhost:8071/userinfo
            user-name-attribute: name
            jwk-set-uri: http://localhost:8090/token_keys

