spring:
  cloud:
    stream:
      bindings:
        output1-out-0:
          content-type: application/json
          destination: test-topic
        output2-out-0:
          content-type: application/json
          destination: TransactionTopic
        output3-out-0:
          content-type: text/plain
          destination: pull-topic
      rocketmq:
        binder:
          name-server: 192.168.0.173:9876
        bindings:
          output1-out-0:
            producer:
              group: binder-group
              sync: true
          output2-out-0:
            producer:
              group: myTxProducerGroup
              transactional: true
          output3-out-0:
            producer:
              group: pull-binder-group
      function:
#        bindings:
#          output1-out-0: output1
#          output2-out-0: output2
#          output3-out-0: output3
        definition: output1;output2;output3
logging:
  level:
    com:
      alibaba:
        cloud:
          stream:
            binder:
              rocketmq: INFO